### ISSUE TITLE
Unknown error occured during Garmin Connect Client login

### ISSUE THREAD

**Issue by st20m010** [stratus-ss/garmin-influxdb#1]
First of all thx for the code i was searching for such a thing for my student project :)

I have an error when running the skript:

DEBUG:garminconnect:Login to Garmin Connect using POST url https://sso.garmin.com/sso/signin
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): sso.garmin.com:443

I don't think direct login via browser https://sso.garmin.com/sso/signin is supported. 
I cant even log in manually with the right email and password (It works on https://connect.garmin.com/signin/ )

An earlier closed issue was solved with installing OpenSSL (https://github.com/cyberjunky/python-garminconnect/issues/14), but it didnt solve the issue for me.
I have garminconnect 0.1.16

ps:: I am a beginner programmer so could be just a stupid mistake from my side.

**Comment by stratus-ss** [comment]
These are not errors simply a debug/info message. The script runs as expected. I am actually running it right now in fact

Are you seeing failures somewhere?

**Comment by st20m010** [comment]
yep totaly my bad thanks!
still having some issues, but that is with my inluxdb i think.
(getting only 2 datapoints exportet) ;D

but that is totaly my issue!
thanks:)
