### ISSUE TITLE
Unauthorized

### ISSUE THREAD

**Issue by Curtis777** [stratus-ss/garmin-influxdb#2]
When starting the script it logs in into garmin and tries to login into my influxDB 2.0  but always says "401 unauthorized " 
any known troubles on this ?

**Comment by stratus-ss** [comment]
is the trouble on Garmin's side or Influx?

**Comment by peejaychilds** [comment]
The influxdb python module in use is for influxdb v1.

I believe to use with v2 you may need to create a 'v1' user.

https://docs.influxdata.com/influxdb/v2.6/reference/cli/influx/v1/auth/create/

I did this ..
```
influx v1 auth create --username v1user --org testorg --write-bucket 51924e85035d08ee --password v1passxxx --token mytoken
```

and in garmin-to-influxdb.py I have

```
influx_server = "my-influxv2-server"
influx_port = 8086
influx_username = "v1user"
influx_password = "v1passxxx"
influx_db = "mybucket"
```

and it works well for me

**Comment by stratus-ss** [comment]
interesting. I am using Chronograf (Version: 1.9.4) to manage my influxdb. in that way this has been abstracted from me

**Comment by Curtis777** [comment]
I will give it a try,
It's definitely a influx error.
I see the successful login to garmin
I will let you know the results

**Comment by Curtis777** [comment]
my influxdb login should work.
so maybe there is another problem.

Anybody's able to help ?

**Comment by peejaychilds** [comment]
Did you create a v1 username/password with your influx?

**Comment by Curtis777** [comment]
yeah, created sucessfull.
but now when i run the script it stops with:
influxdb.exeptions.InfluxDBClientError: 404: {"code":"not found","message":"no dbrp mapping found"}

**Comment by stratus-ss** [comment]
closing this as stale
