### ISSUE TITLE
Add Weight Data

### ISSUE THREAD

**Issue by esmoyer** [stratus-ss/garmin-influxdb#4]
Hey @stratus-ss, I am working to try and add weight data but using Postman can't seem to get the GET commands to work. What are you using in https://github.com/stratus-ss/garmin-influxdb/issues/3#issuecomment-1724319800 to get these endpoints and what URL are you using? I have tried connnect.garmin.com and connectapi.garmin.com but just get a "bad request" error no matter how I structure things, even when using my credentials. Any insight would be appreciated!

**Comment by esmoyer** [comment]
Disregard! This ended up being way easier than I thought it was going to be. 

I was poking around the python-garminconnect repo and found they have an option to call for stats AND body. So just changing [line 246](https://github.com/stratus-ss/garmin-influxdb/blob/3963734c92cf085fc89629cdd24aff85966b38d1/garmin-to-influxdb.py#L246C20-L246C20): 
`client_get_stats = 'client.get_stats("%s")' % day` to `client_get_stats = 'client.get_stats_and_body("%s")' % day` will pull the body comp data and then just modified:

```
    daily_stats = {
        "total_burned_calories": stats['totalKilocalories'],
        "current_date": time.strftime(influxdb_time_format, time.localtime(daily_stats_date)),
        "total_steps": stats['totalSteps'],
        "daily_step_goal": stats['dailyStepGoal'],
        "highly_active_minutes": stats['highlyActiveSeconds'],
        "moderately_active_minutes": stats['activeSeconds'],
        "sedentary_minutes": stats['sedentarySeconds']
    }
```

to add

```
        "daily_weight": stats['weight'], #manual added
        "daily_bodywater": stats['bodyWater'], #manual added
        "daily_bmi": stats['bmi'], #manual added
        "daily_bonemass": stats['boneMass'], #manual added
        "daily_physiquerating": stats['physiqueRating'], #manual added
        "daily_visceralfat": stats['visceralFat'], #manual added
        "daily_metabolicage": stats['metabolicAge'], #manual added
        "bodyfat": stats['bodyFat'] #manual added
```

and voila! Got my weight and body comp stats coming into Influx!

**Comment by stratus-ss** [comment]
thanks for sharing. I suppose it could be an option that you pass in to turn that on. I don't think its reasonable to make it a default, but I would be open to having it be a launch arg
